### PR TITLE
feat: support passing additional headers upstream.

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by enj** [comment]
/hold

This repo is frozen to feature changes until OS4 ships.  Also, this is not a general purpose proxy.  We are unlikely to accept such a feature request.

**Comment by chirino** [comment]
This would come in handy for Fuse Online which is a middleware product that exclusively runs on openshift. Is the openshift team replacing the oauth proxy with something else?

**Comment by chirino** [comment]
@mrogers950 @enj OS4 has shipped.  Have you guys had time to review this PR yet?

**Comment by enj** [comment]
I do not see how such data passing is the responsibility of OAuth proxy.  If you want the upstream to know of some configuration, then pass that configuration to it directly.

Expanding the API surface of this proxy must be justified with a use case that is aligned with what the proxy actually does (i.e. gate network access to apps via the OpenShift OAuth stack).

**Comment by chirino** [comment]
There are several use cases where this could be handy:
* Run an OAuth proxy per tenant, have the proxy set a tenant id header to identify the tenant to the upstream app
* Pass a custom app secret between the proxy and the upstream in case you want to make sure only the oauth proxy is allow to send the upstream traffic.

**Comment by enj** [comment]
>     * Run an OAuth proxy per tenant, have the proxy set a tenant id header to identify the tenant to the upstream app

Again, just pass the configuration to the upstream app directly.

>     * Pass a custom app secret between the proxy and the upstream in case you want to make sure only the oauth proxy is allow to send the upstream traffic.

mTLS between the proxy and the upstream is the correct approach for such a use case.  `localhost` is generally used to avoid malicious traffic from outside the pod.

Sorry but we will not be increasing the surface area for OAuth proxy to support this.  Please reach out to me on the CoreOS Slack if you want to discuss further.

/close

**Pull request closed without merging**
