### PR TITLE
Bug 1748212: [4.1]: Tighten cipher usage

### PR DESCRIPTION
**Pull request by stlaz**
Use the cipher suites that are provided by the OpenShift library-go
as the reasonable defaults.

cc @enj @mrogers950 

-----
I think I'll need to create separate bugzillas for each the backport, the original fix included...

### CODE REVIEW

**Comment by eparis** [comment]
This PR has no review, no bug attached (which depends on a 4.2 bug), and thus no QE review in master. All of these things need done.

**Comment by stlaz** [comment]
Added a BZ and the fix to travis CI so that the tests should pass now.

**Comment by stlaz** [comment]
Travis was still using the old config file, trying to bump go version for its builds to see if this makes it use the new config instead

**Pull request merged**
