### PR TITLE
Fix handling of redirect URI with --skip-provider-button 

### LINKED ISSUE #18: Using skip-provider-button along with proxy-prefix results in non-working setup
I have an app running on <host>/<basePath>.  When I set -proxy-prefix to <basePath>, the authentication process works correctly.  However, when I also introduce -skip-provider-button, after I perform the login (which seems to work just fine), I am redirected to a URL that omits the /<basePath> portion, which fails.

Expected, after login, the redirect goes to <host>/<basePath>.

This seems to be the same issue reported in:  https://github.com/bitly/oauth2_proxy/issues/327

### PR DESCRIPTION
**Pull request by simo5**
Cherry-pick https://github.com/bitly/oauth2_proxy/pull/395

Fixes #18

### CODE REVIEW

**Comment by simo5** [comment]
@crobby @mrogers950 PTAL

**Comment by mrogers950** [comment]
Should this come with the additional logic as mentioned in https://github.com/bitly/oauth2_proxy/pull/395#issuecomment-333322613 ?

**Comment by jimmidyson** [comment]
Was just about to ask about this being merged from upstream - thanks! Any idea when this will be available in a Docker image, either on Docker Hub or productized?

**Comment by simo5** [comment]
@jimmidyson unless it is critical I think we'll release after 3.7 is out

**Pull request merged**
