### PR TITLE
Remove dead TLS client CA loading code

### PR DESCRIPTION
**Pull request by mrogers950**
This loading now happens later on in ServeHTTPS()

### CODE REVIEW

**Comment by mrogers950** [comment]
@simo5 any objections to killing this piece of code?

**Comment by simo5** [comment]
how is it dead ?

**Comment by mrogers950** [comment]
Unless I'm missing something fundamental, options is set up with the client CA files but not assigned to a member of the returning OAuthProxy. Digging into the git history it was assigned at one point, but before the fork.

**Comment by simo5** [comment]
I see it is used directly in httpd.go
/lgtm

**Pull request merged**
