### PR TITLE
honor KUBERNETES_SERVICE_PORT

### PR DESCRIPTION
**Pull request by jcantrill**
This PR makes the provider honor the KUBERNETES_SERVICE_PORT var

### CODE REVIEW

**Comment by enj** [comment]
go fmt please

**Comment by enj** [comment]
Still needs `go fmt` from what I can see:

image

**Comment by enj** [comment]
/uncc

@stlaz @sttts @mfojtik

**Comment by jcantrill** [comment]
@mfojtik ping

**Comment by sttts** [comment]
Why is this need?

**Comment by sttts** [comment]
/close

until we have a reason to change it.

**Pull request closed without merging**
