### PR TITLE
Add log in style

### PR DESCRIPTION
**Pull request by rhamilto**
Need to test to ensure it works as expected.  @jwforres suggested @enj
may be able to instruct me on how to do so.

screenshots of the straight html
screen shot 2017-12-11 at 5 18 49 pm

localhost_8080_error html

### CODE REVIEW

**Comment by mrogers950** [comment]
@rhamilto cool! you can make a test deployment using oauth-proxy/contrib/sidecar.yaml , just change the oauth-proxy spec to point to your test docker repo/image. This will not show the custom login though, to see that you would also need to add -htpasswd-file=/path/to/htpasswdfile to the oauth-proxy args and a configMap with the htpasswd contents.

**Comment by rhamilto** [comment]
Thanks, @mrogers950.  Given my lack of familiarity with this repo, is it possible you or someone else could test my changes?  I'm having a hard time deciphering how to do so.

**Comment by mrogers950** [comment]
@rhamilto Sure, I tested your changes and the design looks as it should (including the htpasswd login box). One gripe is maybe the login boxes should be closer together when they are both displayed.
login

**Comment by rhamilto** [comment]
Fantastic.  Thanks, @mrogers950!  Both log in boxes should not be displayed, so we've got a bug.  I see the issue.  Let me fix.

**Comment by mrogers950** [comment]
@rhamilto The previous template shows both boxes. I think we want to keep that behavior as you can log in with either an OpenShift login or directly with the htpasswd contents when configured as such.

**Comment by rhamilto** [comment]
Spacing bug addressed.  Thanks, @mrogers950!

**Comment by jwforres** [comment]
@mrogers950 need anything else or is this good to merge?

**Comment by mrogers950** [comment]
@jwforres @rhamilto I'm wondering if this this page will display properly on a mobile screen.. Is it possible to confirm there will not be any issues on mobile?

**Comment by rhamilto** [comment]
> @jwforres @rhamilto I'm wondering if this this page will display properly on a mobile screen.. Is it possible to confirm there will not be any issues on mobile?

The page is fully responsive and adapts to the size of the screen.  Here are a couple of quick screenshots for reference.

iPhone 5
_users_rhamilto_desktop_log-in html iphone 5

iPhone 6Plus
_users_rhamilto_desktop_log-in html iphone 6 plus

**Comment by mrogers950** [comment]
@rhamilto perfect, thanks!

**Pull request merged**
