### PR TITLE
Bug 1788419: bump kube to 1.17, use gomod

### PR DESCRIPTION
**Pull request by stlaz**
Latest kube-deps bump was in November 2017 and it most probably was taken from master...

### CODE REVIEW

**Comment by stlaz** [comment]
/test e2e-aws
`listing hosted zones: Throttling: Rate exceeded\n\tstatus code: 400` <-- looks like we're hitting AWS limits

**Comment by deads2k** [comment]
I'm fine with the change, it's good in and of itself.  It's not obvious to me why you think this fixes your problem though.

/lgtm

**Comment by LorbusChris** [comment]
@stlaz you may want to update the Go version used by Travis to 1.13 as well (https://github.com/openshift/oauth-proxy/blob/master/.travis.yml#L4)

**Comment by stlaz** [comment]
@LorbusChris thanks for the suggestion.

I am not sure openshift 3.9, which is being built there, could take it. My plan is to move away from Travis anyway, and use our common testing machinery which sets its own real cluster up soon, so I'd stick with the go version we've got there for now.

**Comment by LorbusChris** [comment]
Oh I missed that it's still on 3.9, nevermind then :)

**Comment by stlaz** [comment]
/hold
I just noticed oauth-proxy is in error backoff for machine-config-demons

**Comment by stlaz** [comment]
fixed config evaluation when no client CA is specified for delegated auth and replaced `nil` context for `Authorize()` call with `context.Background()`

**Comment by stlaz** [comment]
/retest
getting rate exceeded again

**Comment by stlaz** [comment]
/hold cancel
fixed

**Pull request merged**
