### PR TITLE
Issue 107: Add option to pass authorization bearer to upstream

### LINKED ISSUE #107: Passing OAuth access_token to upstream via Authorisation header (rather than X-Forwarded-Access-Token)
In our use-case, we want to use oauth-proxy to protect a user-facing application (HTML/JS single page app).

oauth-proxy will be used to allow the user to authenticate against the OpenShift OAuth server, serve the application's static content, and provide a proxy to an API server.   The user's interactions with the application will cause API calls to be made.   The application won't be in possession of the access_token, so I wanted to rely on oauth-proxy to argument the authenticated request with the authentication user's access token as it traversed the oauth-proxy.

I have found `--pass-access-token=true` which does almost what I want, however the API server in question does not understand X-Forwarded-Access-Token.  I desire a version of the `--pass-access-token` option that would pass OAuth access_token of the authenticated user to upstream via Authorisation header formatted in the bearer format..

I can't change the API server to understand X-Forwarded-Access-Token (the API server in question is the Kubernetes API server itself).

Is there another way to use oauth-proxy that would achieve the same ends?  Alternatively, I would be happy to submit a PR.

Thanks in advance.

### PR DESCRIPTION
**Pull request by InfoSec812**
Resolves #107 

This adds a new option `--pass-auth-bearer` which causes the proxy to pass the `Authorization: Bearer <TOKEN>` header to upstreams.

### CODE REVIEW

**Comment by InfoSec812** [comment]
Interesting... The tests pass for me locally when running `go test`

**Comment by enj** [comment]
/hold

I do not believe this is a use case we want to support.

**Comment by InfoSec812** [comment]
@enj I'd like to understand your reasoning... In my mind, something like this is the same argument as using Istio/Envoy to implement circuit breakers. Instead of having to write custom code to implement OAuth in applications it becomes a deployment detail and reduces cognitive load, developer overhead, and application complexity.

**Comment by k-wall** [comment]
@enj  we too have a desire for this feature.  I put a summary of our use-case in #107.  Currently we need to deploy a HTTPD sidecar behind oauth-proxy to rewrite the headers of the API requests X-Forwarded-Access-Token => Authorization "Bearer...".   This is ugly.   If we had @InfoSec812's feature, this ugliness goes away.

**Comment by mrogers950** [comment]
Does it have to be a conversion to an Authorization header or would it be enough to make it so that there is a way to change "X-Forwarded-Access-Token" to something else? Sorry, we do have some hesitation because our long term goal with this project is to rewrite it to a minimal OpenShift proxy that is stripped down to its core functionality that is suitable for the OpenShift components that consume it. We want to avoid adding a lot of customization if we can help it, in its current state there is already too many options. We did not intend for this project to be a swiss army knife proxy and want to trim it down.

**Comment by InfoSec812** [comment]
@mrogers950 I would say that for **me** the order of preference would be:

1. OpenShift API and K8s API to support `X-Forwarded-Access-Token` (Seems unlikely near-term)
2. Allow a configurable header to pass the OAuth token
3. Keep the change as submitted

If you like, I can resubmit modifying the functionality of the `X-Forwarded-Access-Token`

**Comment by k-wall** [comment]
> @mrogers950 I would say that for **me** the order of preference would be:
> 
> 1. OpenShift API and K8s API to support `X-Forwarded-Access-Token` (Seems unlikely near-term)
> 2. Allow a configurable header to pass the OAuth token
> 3. Keep the change as submitted
> 
> If you like, I can resubmit modifying the functionality of the `X-Forwarded-Access-Token`

@mrogers950, we (EnMasse.io) too are using oauth-proxy to proxy the OpenShift API and K8s APIs.  My preferences are the same as @InfoSec812.

**Comment by mrogers950** [comment]
@InfoSec812 @k-wall I'd accept a solution like #2 (not sure how @enj feels about it). We should have the default header remain as X-Forwarded-Access-Token and let it change with an optional flag like --token-header-name or similar.

**Comment by InfoSec812** [comment]
@mrogers950 Makes sense. Don't break the existing functionality, but allow overriding it when the user wants to. I will see if I can modify this PR or perhaps submit as a new PR.

**Comment by InfoSec812** [comment]
Oh! Wait... That won't work... The "Authorization" header needs to be in the form of "Bearer <TOKEN>" and not just the bare token.  So, even if I did implement this as requested, OpenShift and K8s wouldn't accept it.

**Comment by enj** [comment]
/uncc

@stlaz @sttts @mfojtik

**Pull request closed without merging**
